---
name: Kocom Wallpad w/ RS485
version: 2024.02
slug: kocom
description: Kocom Wallpad for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/hadonga/HA_kocom_addons
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom.cfg 설정파일: true
schema:
  share/kocom.cfg 설정파일: bool